# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xa7a35tcpg236-1I

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/o_ark/Project_265/Project_265.cache/wt [current_project]
set_property parent.project_path C:/Users/o_ark/Project_265/Project_265.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/o_ark/Project_265/Project_265.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/baud_rate_generator.v
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/clock_digit_rom.v
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/clock_divider.v
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/digital_calendar.v
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/digital_clock.v
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/pixel_gen.v
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/seven_segment.v
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/top_clk_cal.v
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/uart_14_byte_store.v
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/uart_19_byte_transmit.v
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/uart_demod.v
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/uart_mod.v
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/uart_rx.v
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/uart_tx.v
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/vga_controller.v
  C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/sources_1/imports/implemented_design/design_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/constrs_1/imports/implemented_design/const_vga_clk_cal.xdc
set_property used_in_implementation false [get_files C:/Users/o_ark/Downloads/proje_son/project_1/project_1.srcs/constrs_1/imports/implemented_design/const_vga_clk_cal.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_top -part xa7a35tcpg236-1I


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_top_utilization_synth.rpt -pb design_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
